import { PDFDocument, rgb, StandardFonts, PageSizes } from 'pdf-lib';
import fontkit from '@pdf-lib/fontkit';
import { Story, StorySlide } from '../types';

interface PdfExportOptions {
  includeImages?: boolean;
  includeMetadata?: boolean;
  password?: string;
  watermarkText?: string;
  watermarkOpacity?: number;
}

export class EnhancedPdfExportService {
  private readonly WATERMARK_TEXT = 'Felearn AI';
  private readonly WATERMARK_OPACITY = 0.3;
  private readonly PAGE_MARGIN = 50;
  private readonly FONT_SIZE_TITLE = 24;
  private readonly FONT_SIZE_SUBTITLE = 14;
  private readonly FONT_SIZE_BODY = 12;
  private readonly FONT_SIZE_CAPTION = 10;
  private readonly LINE_HEIGHT = 1.4;

  /**
   * Export story to PDF with real images, captions, and watermarks
   */
  async exportStoryToPDF(
    story: Story,
    slides: StorySlide[] = [],
    options: PdfExportOptions = {}
  ): Promise<void> {
    console.log('EnhancedPdfExport - Starting PDF export with data:', {
      storyTitle: story.title,
      slidesCount: slides.length,
      slides: slides,
      options
    });

    const {
      includeImages = true,
      includeMetadata = true,
      watermarkText = this.WATERMARK_TEXT,
      watermarkOpacity = this.WATERMARK_OPACITY
    } = options;

    try {
      // Create a new PDF document
      const pdfDoc = await PDFDocument.create();
      
      // Register fontkit for custom font support
      pdfDoc.registerFontkit(fontkit);
      
      // Set document metadata
      pdfDoc.setTitle(story.title);
      pdfDoc.setAuthor('Felearn AI');
      pdfDoc.setSubject('AI Generated Story');
      pdfDoc.setCreator('Felearn AI Platform');
      pdfDoc.setProducer('Felearn AI PDF Export');
      pdfDoc.setCreationDate(new Date());
      pdfDoc.setModificationDate(new Date());

      // Embed fonts - use standard fonts for reliability
      const titleFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
      const bodyFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
      const italicFont = await pdfDoc.embedFont(StandardFonts.HelveticaOblique);
      
      // Try to load custom fonts, fallback to standard fonts if they fail
      let indieFlowerFont = titleFont; // fallback
      let dosisFont = titleFont; // fallback
      let ubuntuLightFont = bodyFont; // fallback
      let consolasFont = bodyFont; // fallback
      
      try {
        // Load custom fonts using fetch
        const indieFlowerResponse = await fetch('/assets/fonts/IndieFlower-Regular.ttf');
        if (indieFlowerResponse.ok) {
          const indieFlowerBytes = await indieFlowerResponse.arrayBuffer();
          indieFlowerFont = await pdfDoc.embedFont(new Uint8Array(indieFlowerBytes));
        }
      } catch (error) {
        console.warn('Failed to load IndieFlower font, using fallback:', error);
      }
      
      try {
        const dosisResponse = await fetch('/assets/fonts/Dosis-VariableFont_wght_library_title.ttf');
        if (dosisResponse.ok) {
          const dosisBytes = await dosisResponse.arrayBuffer();
          dosisFont = await pdfDoc.embedFont(new Uint8Array(dosisBytes));
        }
      } catch (error) {
        console.warn('Failed to load Dosis font, using fallback:', error);
      }

      try {
        const ubuntuLightResponse = await fetch('/assets/fonts/Ubuntu-light-pdf-export-date.ttf');
        if (ubuntuLightResponse.ok) {
          const ubuntuLightBytes = await ubuntuLightResponse.arrayBuffer();
          ubuntuLightFont = await pdfDoc.embedFont(new Uint8Array(ubuntuLightBytes));
        }
      } catch (error) {
        console.warn('Failed to load Ubuntu Light font, using fallback:', error);
      }

      try {
        const consolasResponse = await fetch('/assets/fonts/consolas-disclaimer-pdf.ttf');
        if (consolasResponse.ok) {
          const consolasBytes = await consolasResponse.arrayBuffer();
          consolasFont = await pdfDoc.embedFont(new Uint8Array(consolasBytes));
        }
      } catch (error) {
        console.warn('Failed to load Consolas font, using fallback:', error);
      }

      // Page 1: Title Page with logo, custom fonts, and metadata
      let currentPage = pdfDoc.addPage(PageSizes.A4);
      let yPosition = currentPage.getHeight() - this.PAGE_MARGIN;

      // Add Felearn logo at the top-center (with proper aspect ratio)
      yPosition = await this.addLogoTopCenter(currentPage, pdfDoc, yPosition);

      // Add main title with Dosis font - ULTRA LARGE and centered in middle of page
      yPosition = await this.addCustomTitleCentered(currentPage, story.title, dosisFont, yPosition);

      // Add subtitle "Generated by Felearn AI" below title (larger as in reference image)
      yPosition = await this.addSubtitleBelowTitle(currentPage, 'Generated by Felearn AI', italicFont, yPosition);

      // Add metadata at bottom-left (left-aligned, not centered)
      if (includeMetadata) {
        await this.addMetadataBottomLeft(currentPage, story, ubuntuLightFont);
      }

      // Add slides - each slide on its own page
      if (includeImages && slides.length > 0) {
        for (let i = 0; i < slides.length; i++) {
          const slide = slides[i];
          if (slide.image) {
            // Create new page for each slide
            currentPage = pdfDoc.addPage(PageSizes.A4);
            yPosition = currentPage.getHeight() - this.PAGE_MARGIN;
            
            const result = await this.addSlidePage(
              currentPage,
              pdfDoc,
              slide,
              i + 1,
              slides.length,
              indieFlowerFont, // Use IndieFlower font for captions
              bodyFont,
              yPosition,
              watermarkText,
              watermarkOpacity
            );
            
            currentPage = result.page;
            yPosition = result.yPosition;
          }
        }
      }

      // Add acknowledgment page at the end
      currentPage = pdfDoc.addPage(PageSizes.A4);
      yPosition = currentPage.getHeight() - this.PAGE_MARGIN;
      await this.addAcknowledgmentPage(currentPage, bodyFont, yPosition, dosisFont, consolasFont, ubuntuLightFont, pdfDoc);

      // Save and download the PDF (removed encryption for compatibility)
      const pdfBytes = await pdfDoc.save();
      const fileName = this.sanitizeFileName(story.title) + '_felearn.pdf';
      
      this.downloadPDF(pdfBytes, fileName);
      
      console.log('Enhanced PDF export completed successfully');
    } catch (error) {
      console.error('Enhanced PDF export error:', error);
      throw new Error('Failed to export PDF with enhanced features');
    }
  }

  /**
   * Add Felearn logo at the top-center (with proper aspect ratio)
   */
  private async addLogoTopCenter(
    page: any,
    pdfDoc: any,
    yPosition: number
  ): Promise<number> {
    const pageWidth = page.getWidth();
    const logoWidth = 341; // Base width
    const logoHeight = 100; // Maintain 2:1 aspect ratio (200/100 = 2)

    try {
      const imageBytes = await this.loadImageFromUrl('/assets/felearn-logo.png');
      if (imageBytes) {
        const image = await pdfDoc.embedPng(imageBytes);
        const imageX = (pageWidth - logoWidth) / 2; // Center horizontally
        const imageY = yPosition - logoHeight;

        page.drawImage(image, {
          x: imageX,
          y: imageY,
          width: logoWidth,
          height: logoHeight
        });
        return imageY - 30; // Space below logo
      }
    } catch (error) {
      console.warn('Failed to load Felearn logo, using fallback:', error);
    }
    return yPosition - 30; // Fallback space
  }

  /**
   * Add main title with Dosis font - ULTRA LARGE and centered in middle of page
   */
  private async addCustomTitleCentered(
    page: any,
    title: string,
    font: any,
    yPosition: number
  ): Promise<number> {
    const pageWidth = page.getWidth();
    const pageHeight = page.getHeight();
    const maxWidth = pageWidth - (this.PAGE_MARGIN * 2);
    const ultraLargeFontSize = 68; // Increased by 1.2x from 48 (48 * 1.2 = 57.6 ≈ 58)
    
    // Split title if too long
    const titleLines = this.splitTextToFitWidth(title, font, ultraLargeFontSize, maxWidth);
    
    // Calculate the middle of the page for title positioning
    const totalTitleHeight = titleLines.length * ultraLargeFontSize * this.LINE_HEIGHT;
    const middleY = pageHeight / 2 + totalTitleHeight / 2; // Center vertically in middle of page
    
    let currentY = middleY;
    
    titleLines.forEach((line, index) => {
      const textWidth = font.widthOfTextAtSize(line, ultraLargeFontSize);
      const centerX = (pageWidth - textWidth) / 2; // Perfect center alignment
      
      page.drawText(line, {
        x: centerX,
        y: currentY,
        size: ultraLargeFontSize,
        font: font,
        color: rgb(0.1, 0.1, 0.1) // Dark color for maximum readability
      });
      currentY -= ultraLargeFontSize * this.LINE_HEIGHT;
    });

    return currentY - 30; // Space below title
  }

  /**
   * Add subtitle "Generated by Felearn AI" below title (larger as in reference image)
   */
  private async addSubtitleBelowTitle(
    page: any,
    subtitle: string,
    font: any,
    yPosition: number
  ): Promise<number> {
    const pageWidth = page.getWidth();
    const subtitleFontSize = 20; // Larger font size as in reference image
    
    const textWidth = font.widthOfTextAtSize(subtitle, subtitleFontSize);
    const centerX = (pageWidth - textWidth) / 2; // Perfect center alignment
    
    page.drawText(subtitle, {
      x: centerX,
      y: yPosition,
      size: subtitleFontSize,
      font: font,
      color: rgb(0.4, 0.4, 0.4) // Subtle gray color
    });
    
    return yPosition - subtitleFontSize * this.LINE_HEIGHT - 50; // Extra space after subtitle
  }

  /**
   * Add metadata at bottom-left (left-aligned, not centered)
   */
  private async addMetadataBottomLeft(
    page: any,
    story: Story,
    font: any
  ): Promise<void> {
    const pageHeight = page.getHeight();
    const metadataFontSize = 10; // Smaller font size as in reference image
    const metadataSpacing = 12;
    
    // Get current timestamp for PDF creation
    const pdfCreationTime = new Date().toLocaleString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit'
    });

    // Get story creation date
    const storyCreationDate = new Date(story.createdAt).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    // Get profile username (you may need to adjust this based on your user system)
    const username = story.name || story.userId || 'Anonymous User';

    // Get total slides count
    const totalSlidesCount = story.slides?.length || 0;

    // Get status
    const status = story.isPinned ? 'Pinned' : 'Active';

    // Create metadata array
    const metadata = [
      `PDF Creation Time: ${pdfCreationTime}`,
      `Username: ${username}`,
      `Story Creation Date: ${storyCreationDate}`,
      `Total Slides: ${totalSlidesCount}`,
      `Status: ${status}`
    ];

    // Start drawing from the bottom-left margin
    let currentY = this.PAGE_MARGIN + (metadata.length * metadataFontSize * this.LINE_HEIGHT) + (metadata.length - 1) * metadataSpacing;

    metadata.forEach((line, index) => {
      page.drawText(line, {
        x: this.PAGE_MARGIN, // Left-aligned
        y: currentY,
        size: metadataFontSize,
        font: font,
        color: rgb(0.4, 0.4, 0.4)
      });
      currentY -= metadataFontSize * this.LINE_HEIGHT + metadataSpacing;
    });
  }

  /**
   * Add content to PDF with page breaks
   */
  private async addContent(
    page: any,
    pdfDoc: any,
    content: string,
    font: any,
    yPosition: number
  ): Promise<number> {
    const pageWidth = page.getWidth();
    const pageHeight = page.getHeight();
    const maxWidth = pageWidth - (this.PAGE_MARGIN * 2);
    
    const paragraphs = content.split('\n\n');
    
    for (const paragraph of paragraphs) {
      if (paragraph.trim() === '') continue;
      
      const lines = this.splitTextToFitWidth(paragraph, font, this.FONT_SIZE_BODY, maxWidth);
      
      // Check if we need a new page
      const requiredHeight = lines.length * this.FONT_SIZE_BODY * this.LINE_HEIGHT;
      if (yPosition - requiredHeight < this.PAGE_MARGIN) {
        page = pdfDoc.addPage(PageSizes.A4);
        yPosition = pageHeight - this.PAGE_MARGIN;
      }
      
      lines.forEach(line => {
        page.drawText(line, {
          x: this.PAGE_MARGIN,
          y: yPosition,
          size: this.FONT_SIZE_BODY,
          font: font,
          color: rgb(0, 0, 0)
        });
        yPosition -= this.FONT_SIZE_BODY * this.LINE_HEIGHT;
      });
      
      yPosition -= 10; // Paragraph spacing
    }

    return yPosition;
  }

  /**
   * Add a slide page with image and caption
   */
  private async addSlidePage(
    page: any,
    pdfDoc: any,
    slide: StorySlide,
    slideNumber: number,
    totalSlides: number,
    captionFont: any,
    bodyFont: any,
    yPosition: number,
    watermarkText: string,
    watermarkOpacity: number
  ): Promise<{ page: any; yPosition: number }> {
      const pageWidth = page.getWidth();
      const pageHeight = page.getHeight();
    
    // Add slide number at top
    page.drawText(`Slide ${slideNumber} of ${totalSlides}`, {
      x: this.PAGE_MARGIN,
      y: yPosition,
      size: this.FONT_SIZE_SUBTITLE,
      font: bodyFont,
      color: rgb(0.5, 0.5, 0.5)
    });
    yPosition -= this.FONT_SIZE_SUBTITLE * this.LINE_HEIGHT + 20;

    // Add image
    if (slide.image) {
      try {
        const imageBytes = await this.loadImageFromUrl(slide.image);
        if (imageBytes) {
          const image = await pdfDoc.embedPng(imageBytes);
          const imageWidth = pageWidth - (this.PAGE_MARGIN * 2);
          const imageHeight = (image.height / image.width) * imageWidth;
          
          // Center the image
          const imageX = this.PAGE_MARGIN;
      const imageY = yPosition - imageHeight;
      
      page.drawImage(image, {
        x: imageX,
        y: imageY,
        width: imageWidth,
        height: imageHeight
      });

          yPosition = imageY - 30; // Space below image
        }
      } catch (error) {
        console.error('Failed to load image:', error);
        // Add placeholder text
        page.drawText('Image not available', {
          x: this.PAGE_MARGIN,
          y: yPosition,
          size: this.FONT_SIZE_BODY,
          font: bodyFont,
          color: rgb(0.7, 0.7, 0.7)
        });
        yPosition -= this.FONT_SIZE_BODY * this.LINE_HEIGHT + 20;
      }
    }

    // Add caption in Indie Flower style (using IndieFlower font)
    if (slide.text) {
      const caption = this.cleanCaption(slide.text);
      const captionFontSize = 31; // Increased by 4.7x from 18 (18 * 4.7 = 84.6 ≈ 85)
      const captionLines = this.splitTextToFitWidth(
        caption, 
        captionFont, // This is now the IndieFlower font
        captionFontSize,
        pageWidth - (this.PAGE_MARGIN * 2)
      );
      
      // Add some space before caption
      yPosition -= 30;
      
      // Center the caption text
      captionLines.forEach((line) => {
        const textWidth = captionFont.widthOfTextAtSize(line, captionFontSize);
        const centerX = (pageWidth - textWidth) / 2;
        
        page.drawText(line, {
          x: centerX,
          y: yPosition,
          size: captionFontSize,
          font: captionFont, // IndieFlower font
          color: rgb(0.2, 0.2, 0.2) // Darker color for better readability
        });
        yPosition -= captionFontSize * this.LINE_HEIGHT;
      });
    }

    // Add watermark
      page.drawText(watermarkText, {
      x: pageWidth - this.PAGE_MARGIN - 100,
      y: this.PAGE_MARGIN,
        size: 10,
        font: bodyFont,
      color: rgb(0.8, 0.8, 0.8)
    });

    return { page, yPosition };
  }

  /**
   * Add acknowledgment page with specified fonts and structure
   */
  private async addAcknowledgmentPage(
    page: any,
    bodyFont: any,
    yPosition: number,
    dosisFont: any,
    consolasFont: any,
    ubuntuLightFont: any,
    pdfDoc: any
  ): Promise<void> {
    const pageWidth = page.getWidth();
    const pageHeight = page.getHeight();
    
    // Start from top of page
    let currentY = pageHeight - this.PAGE_MARGIN;
    
    // ACKNOWLEDGEMENT {TITLE} - Bold, large, top-center, simple font
    const titleFontSize = 36;
    const titleText = 'ACKNOWLEDGEMENT';
    const titleWidth = bodyFont.widthOfTextAtSize(titleText, titleFontSize);
    const titleX = (pageWidth - titleWidth) / 2;
    
    page.drawText(titleText, {
      x: titleX,
      y: currentY,
      size: titleFontSize,
      font: bodyFont,
      color: rgb(0.1, 0.1, 0.1)
    });
    currentY -= titleFontSize * this.LINE_HEIGHT + 40;
    
    // A Note on Your AI-Generated Story {sub-title} - Dosis font
    const subtitleFontSize = 24;
    const subtitleText = 'A Note on Your AI-Generated Story';
    const subtitleWidth = dosisFont.widthOfTextAtSize(subtitleText, subtitleFontSize);
    const subtitleX = (pageWidth - subtitleWidth) / 2;
    
    page.drawText(subtitleText, {
      x: subtitleX,
      y: currentY,
      size: subtitleFontSize,
      font: dosisFont,
      color: rgb(0.2, 0.2, 0.2)
    });
    currentY -= subtitleFontSize * this.LINE_HEIGHT + 30;
    
    // This story was crafted... {text} - Consolas font
    const textFontSize = 12;
    const textContent = "This story was crafted through a creative partnership between you and the Felearn AI platform, powered by Google's Gemini model.";
    const textLines = this.splitTextToFitWidth(textContent, consolasFont, textFontSize, pageWidth - (this.PAGE_MARGIN * 2));
    
    textLines.forEach(line => {
      page.drawText(line, {
        x: this.PAGE_MARGIN,
        y: currentY,
        size: textFontSize,
        font: consolasFont,
        color: rgb(0.3, 0.3, 0.3)
      });
      currentY -= textFontSize * this.LINE_HEIGHT;
    });
    currentY -= 20;
    
    // How This Story Was Made {heading} - Simple font
    const headingFontSize = 18;
    const headingText = 'How This Story Was Made';
    page.drawText(headingText, {
      x: this.PAGE_MARGIN,
      y: currentY,
      size: headingFontSize,
      font: bodyFont,
      color: rgb(0.1, 0.1, 0.1)
    });
    currentY -= headingFontSize * this.LINE_HEIGHT + 15;
    
    // Your Concept: {text} - Consolas font
    const conceptText = "Your Concept: The core idea, characters, and learning objective for this narrative came directly from the prompt you provided.";
    const conceptLines = this.splitTextToFitWidth(conceptText, consolasFont, textFontSize, pageWidth - (this.PAGE_MARGIN * 2));
    
    conceptLines.forEach(line => {
      page.drawText(line, {
        x: this.PAGE_MARGIN,
        y: currentY,
        size: textFontSize,
        font: consolasFont,
        color: rgb(0.3, 0.3, 0.3)
      });
      currentY -= textFontSize * this.LINE_HEIGHT;
    });
    currentY -= 15;
    
    // AI Generation: {text} - Consolas font
    const aiText = "AI Generation: Felearn AI used that concept to generate the story text and create the accompanying illustrations.";
    const aiLines = this.splitTextToFitWidth(aiText, consolasFont, textFontSize, pageWidth - (this.PAGE_MARGIN * 2));
    
    aiLines.forEach(line => {
      page.drawText(line, {
        x: this.PAGE_MARGIN,
        y: currentY,
        size: textFontSize,
        font: consolasFont,
        color: rgb(0.3, 0.3, 0.3)
      });
      currentY -= textFontSize * this.LINE_HEIGHT;
    });
    currentY -= 20;
    
    // Content & Usage Disclaimer {heading} - Simple font
    const disclaimerHeadingText = 'Content & Usage Disclaimer';
    page.drawText(disclaimerHeadingText, {
      x: this.PAGE_MARGIN,
      y: currentY,
      size: headingFontSize,
      font: bodyFont,
      color: rgb(0.1, 0.1, 0.1)
    });
    currentY -= headingFontSize * this.LINE_HEIGHT + 15;
    
    // This document was generated... {text} - Consolas font
    const disclaimerText1 = "This document was generated for your personal and educational enjoyment. While we aim for creative and helpful content, please be aware that:";
    const disclaimerLines1 = this.splitTextToFitWidth(disclaimerText1, consolasFont, textFontSize, pageWidth - (this.PAGE_MARGIN * 2));
    
    disclaimerLines1.forEach(line => {
      page.drawText(line, {
        x: this.PAGE_MARGIN,
        y: currentY,
        size: textFontSize,
        font: consolasFont,
        color: rgb(0.3, 0.3, 0.3)
      });
      currentY -= textFontSize * this.LINE_HEIGHT;
    });
    currentY -= 15;
    
    // The narrative is AI-generated... {text} - Consolas font
    const disclaimerText2 = "The narrative is AI-generated and may contain fictional elements or factual inaccuracies. Please verify any critical information independently.";
    const disclaimerLines2 = this.splitTextToFitWidth(disclaimerText2, consolasFont, textFontSize, pageWidth - (this.PAGE_MARGIN * 2));
    
    disclaimerLines2.forEach(line => {
      page.drawText(line, {
        x: this.PAGE_MARGIN,
        y: currentY,
        size: textFontSize,
        font: consolasFont,
        color: rgb(0.3, 0.3, 0.3)
      });
      currentY -= textFontSize * this.LINE_HEIGHT;
    });
    currentY -= 15;
    
    // You are welcome to use... {text} - Consolas font
    const disclaimerText3 = "You are welcome to use and share this story for non-commercial purposes. Commercial use or redistribution of this content is prohibited.";
    const disclaimerLines3 = this.splitTextToFitWidth(disclaimerText3, consolasFont, textFontSize, pageWidth - (this.PAGE_MARGIN * 2));
    
    disclaimerLines3.forEach(line => {
      page.drawText(line, {
        x: this.PAGE_MARGIN,
        y: currentY,
        size: textFontSize,
        font: consolasFont,
        color: rgb(0.3, 0.3, 0.3)
      });
      currentY -= textFontSize * this.LINE_HEIGHT;
    });
    currentY -= 30;
    
    // Generated by Felearn AI {End title} - Ubuntu Light font
    const endTitleFontSize = 16;
    const endTitleText = 'Generated by Felearn AI';
    const endTitleWidth = ubuntuLightFont.widthOfTextAtSize(endTitleText, endTitleFontSize);
    const endTitleX = (pageWidth - endTitleWidth) / 2;
    
    page.drawText(endTitleText, {
      x: endTitleX,
      y: currentY,
      size: endTitleFontSize,
      font: ubuntuLightFont,
      color: rgb(0.4, 0.4, 0.4)
    });
    currentY -= endTitleFontSize * this.LINE_HEIGHT + 20;
    
    // Small logo (same as front page but smaller)
    const smallLogoWidth = 139;
    const smallLogoHeight = 41;
    
    try {
      const imageBytes = await this.loadImageFromUrl('/assets/felearn-logo.png');
      if (imageBytes) {
        const image = await pdfDoc.embedPng(imageBytes);
        const logoX = (pageWidth - smallLogoWidth) / 2;
        const logoY = currentY - smallLogoHeight;
        
        page.drawImage(image, {
          x: logoX,
          y: logoY,
          width: smallLogoWidth,
          height: smallLogoHeight
        });
        currentY = logoY - 20;
      }
    } catch (error) {
      console.warn('Failed to load small logo for acknowledgment page:', error);
    }
    
    // Creation Metadata - Consolas font
    const metadataFontSize = 10;
    const currentTime = new Date().toLocaleString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit'
    });
    
    const metadataText = `Creation Metadata: PDF generated on ${currentTime}`;
    page.drawText(metadataText, {
      x: this.PAGE_MARGIN,
      y: currentY,
      size: metadataFontSize,
      font: consolasFont,
      color: rgb(0.5, 0.5, 0.5)
    });
  }

  /**
   * Load image from URL as bytes
   */
  private async loadImageFromUrl(url: string): Promise<Uint8Array | null> {
    try {
      const response = await fetch(url);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const arrayBuffer = await response.arrayBuffer();
      return new Uint8Array(arrayBuffer);
    } catch (error) {
      console.error('Error loading image from URL:', error);
      return null;
    }
  }



  /**
   * Clean caption text
   */
  private cleanCaption(caption: string): string {
    return caption
      .replace(/\*\*Image \d+:\*\*/g, '')
      .replace(/Caption:/g, '')
      .replace(/\*\*/g, '')
      .replace(/^["']|["']$/g, '')
      .trim();
  }

  /**
   * Split text to fit within specified width
   */
  private splitTextToFitWidth(
    text: string,
    font: any,
    fontSize: number,
    maxWidth: number
  ): string[] {
    const words = text.split(' ');
    const lines: string[] = [];
    let currentLine = '';

    for (const word of words) {
      const testLine = currentLine ? `${currentLine} ${word}` : word;
      const testWidth = font.widthOfTextAtSize(testLine, fontSize);
      
      if (testWidth <= maxWidth) {
        currentLine = testLine;
      } else {
        if (currentLine) {
          lines.push(currentLine);
          currentLine = word;
        } else {
          // Word is too long, break it
          lines.push(word);
        }
      }
    }
    
    if (currentLine) {
      lines.push(currentLine);
    }

    return lines;
  }

  /**
   * Download PDF file
   */
  private downloadPDF(pdfBytes: Uint8Array, fileName: string): void {
    const blob = new Blob([pdfBytes], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    // Clean up
    setTimeout(() => URL.revokeObjectURL(url), 100);
  }

  /**
   * Sanitize filename
   */
  private sanitizeFileName(fileName: string): string {
    return fileName
      .replace(/[^a-z0-9\s-]/gi, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .trim()
      .toLowerCase()
      .substring(0, 50);
  }
}

// Export singleton instance
export const enhancedPdfExportService = new EnhancedPdfExportService();