import { PDFDocument, rgb, StandardFonts, PageSizes } from 'pdf-lib';
import fontkit from '@pdf-lib/fontkit';
import { Story, StorySlide } from '../types';

interface PdfExportOptions {
  includeImages?: boolean;
  includeMetadata?: boolean;
  password?: string;
  watermarkText?: string;
  watermarkOpacity?: number;
}

export class EnhancedPdfExportService {
  private readonly WATERMARK_TEXT = 'Felearn AI';
  private readonly WATERMARK_OPACITY = 0.3;
  private readonly PAGE_MARGIN = 50;
  private readonly FONT_SIZE_TITLE = 24;
  private readonly FONT_SIZE_SUBTITLE = 14;
  private readonly FONT_SIZE_BODY = 12;
  private readonly FONT_SIZE_CAPTION = 10;
  private readonly LINE_HEIGHT = 1.4;

  /**
   * Export story to PDF with real images, captions, and watermarks
   */
  async exportStoryToPDF(
    story: Story,
    slides: StorySlide[] = [],
    options: PdfExportOptions = {}
  ): Promise<void> {
    // Starting PDF export

    const {
      includeImages = true,
      includeMetadata = true,
      watermarkText = this.WATERMARK_TEXT,
      watermarkOpacity = this.WATERMARK_OPACITY
    } = options;

    try {
      // Create a new PDF document
      const pdfDoc = await PDFDocument.create();

      // Register fontkit for custom font support
      pdfDoc.registerFontkit(fontkit);

      // Set document metadata
      pdfDoc.setTitle(story.title);
      pdfDoc.setAuthor('Felearn AI');
      pdfDoc.setSubject('AI Generated Story');
      pdfDoc.setCreator('Felearn AI Platform');
      pdfDoc.setProducer('Felearn AI PDF Export');
      pdfDoc.setCreationDate(new Date());
      pdfDoc.setModificationDate(new Date());

      // Embed fonts - use standard fonts for reliability
      const titleFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
      const bodyFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
      const italicFont = await pdfDoc.embedFont(StandardFonts.HelveticaOblique);

      // Try to load custom fonts, fallback to standard fonts if they fail
      let indieFlowerFont = titleFont; // fallback
      let dosisFont = titleFont; // fallback
      let ubuntuLightFont = bodyFont; // fallback
      let consolasFont = bodyFont; // fallback

      try {
        // Load custom fonts using fetch
        const indieFlowerResponse = await fetch('/assets/fonts/IndieFlower-Regular.ttf');
        if (indieFlowerResponse.ok) {
          const indieFlowerBytes = await indieFlowerResponse.arrayBuffer();
          indieFlowerFont = await pdfDoc.embedFont(new Uint8Array(indieFlowerBytes));
        }
      } catch (error) {
        console.warn('Failed to load IndieFlower font, using fallback:', error);
      }

      try {
        const dosisResponse = await fetch('/assets/fonts/Dosis-VariableFont_wght_library_title.ttf');
        if (dosisResponse.ok) {
          const dosisBytes = await dosisResponse.arrayBuffer();
          dosisFont = await pdfDoc.embedFont(new Uint8Array(dosisBytes));
        }
      } catch (error) {
        console.warn('Failed to load Dosis font, using fallback:', error);
      }

      try {
        const ubuntuLightResponse = await fetch('/assets/fonts/Ubuntu-light-pdf-export-date.ttf');
        if (ubuntuLightResponse.ok) {
          const ubuntuLightBytes = await ubuntuLightResponse.arrayBuffer();
          ubuntuLightFont = await pdfDoc.embedFont(new Uint8Array(ubuntuLightBytes));
        }
      } catch (error) {
        console.warn('Failed to load Ubuntu Light font, using fallback:', error);
      }

      try {
        const consolasResponse = await fetch('/assets/fonts/consolas-disclaimer-pdf.ttf');
        if (consolasResponse.ok) {
          const consolasBytes = await consolasResponse.arrayBuffer();
          consolasFont = await pdfDoc.embedFont(new Uint8Array(consolasBytes));
        }
      } catch (error) {
        console.warn('Failed to load Consolas font, using fallback:', error);
      }

      // Page 1: Title Page with logo, custom fonts, and metadata
      let currentPage = pdfDoc.addPage(PageSizes.A4);
      let yPosition = currentPage.getHeight() - this.PAGE_MARGIN;

      // Add Felearn logo at the top-center (with proper aspect ratio)
      yPosition = await this.addLogoTopCenter(currentPage, pdfDoc, yPosition);

      // Add main title with Dosis font - ULTRA LARGE and centered in middle of page
      yPosition = await this.addCustomTitleCentered(currentPage, story.title, dosisFont, yPosition);

      // Add subtitle "Generated by Felearn AI" below title (larger as in reference image)
      yPosition = await this.addSubtitleBelowTitle(currentPage, 'Generated by Felearn AI', italicFont, yPosition);

      // Add metadata at bottom-left (left-aligned, not centered)
      if (includeMetadata) {
        await this.addMetadataBottomLeft(currentPage, story, ubuntuLightFont);
      }

      // Add slides - each slide on its own page
      if (includeImages && slides.length > 0) {
        for (let i = 0; i < slides.length; i++) {
          const slide = slides[i];
          if (slide.image) {
            // Create new page for each slide
            currentPage = pdfDoc.addPage(PageSizes.A4);
            yPosition = currentPage.getHeight() - this.PAGE_MARGIN;

            const result = await this.addSlidePage(
              currentPage,
              pdfDoc,
              slide,
              i + 1,
              slides.length,
              indieFlowerFont, // Use IndieFlower font for captions
              bodyFont,
              yPosition,
              watermarkText,
              watermarkOpacity
            );

            currentPage = result.page;
            yPosition = result.yPosition;
          }
        }
      }

      // Add acknowledgment page at the end
      currentPage = pdfDoc.addPage(PageSizes.A4);
      yPosition = currentPage.getHeight() - this.PAGE_MARGIN;
      await this.addAcknowledgmentPage(currentPage, bodyFont, yPosition, dosisFont, consolasFont, ubuntuLightFont, pdfDoc);

      // Save and download the PDF (removed encryption for compatibility)
      const pdfBytes = await pdfDoc.save();
      const fileName = this.sanitizeFileName(story.title) + '_felearn.pdf';

      this.downloadPDF(pdfBytes, fileName);

      console.log('Enhanced PDF export completed successfully');
    } catch (error) {
      console.error('Enhanced PDF export error:', error);
      throw new Error('Failed to export PDF with enhanced features');
    }
  }

  /**
   * Add Felearn logo at the top-center (with proper aspect ratio)
   */
  private async addLogoTopCenter(
    page: any,
    pdfDoc: any,
    yPosition: number
  ): Promise<number> {
    const pageWidth = page.getWidth();
    const logoWidth = 341; // Base width
    const logoHeight = 100; // Maintain 2:1 aspect ratio (200/100 = 2)

    try {
      const imageBytes = await this.loadImageFromUrl('/assets/felearn-logo.png');
      if (imageBytes) {
        const image = await pdfDoc.embedPng(imageBytes);
        const imageX = (pageWidth - logoWidth) / 2; // Center horizontally
        const imageY = yPosition - logoHeight;

        page.drawImage(image, {
          x: imageX,
          y: imageY,
          width: logoWidth,
          height: logoHeight
        });
        return imageY - 30; // Space below logo
      }
    } catch (error) {
      console.warn('Failed to load Felearn logo, using fallback:', error);
    }
    return yPosition - 30; // Fallback space
  }

  /**
   * Add main title with Dosis font - ULTRA LARGE and centered in middle of page
   * With fallback for long titles that overflow
   */
  private async addCustomTitleCentered(
    page: any,
    title: string,
    font: any,
    yPosition: number
  ): Promise<number> {
    const pageWidth = page.getWidth();
    const pageHeight = page.getHeight();
    const maxWidth = pageWidth - (this.PAGE_MARGIN * 2);
    let fontSize = 68; // Start with ultra large font size

    // Check if title fits at current font size, reduce if needed
    const titleWidth = font.widthOfTextAtSize(title, fontSize);
    if (titleWidth > maxWidth) {
      // Calculate optimal font size to fit in one line if possible
      const optimalFontSize = Math.floor((maxWidth / titleWidth) * fontSize);
      fontSize = Math.max(optimalFontSize, 32); // Minimum font size of 32px
    }

    // Split title if still too long even at reduced size
    const titleLines = this.splitTextToFitWidth(title, font, fontSize, maxWidth);

    // Calculate the middle of the page for title positioning
    const totalTitleHeight = titleLines.length * fontSize * this.LINE_HEIGHT;
    const middleY = pageHeight / 2 + totalTitleHeight / 2; // Center vertically in middle of page

    let currentY = middleY;

    titleLines.forEach((line, index) => {
      const textWidth = font.widthOfTextAtSize(line, fontSize);
      const centerX = (pageWidth - textWidth) / 2; // Perfect center alignment

      page.drawText(line, {
        x: centerX,
        y: currentY,
        size: fontSize,
        font: font,
        color: rgb(0.1, 0.1, 0.1) // Dark color for maximum readability
      });
      currentY -= fontSize * this.LINE_HEIGHT;
    });

    return currentY - 30; // Space below title
  }

  /**
   * Add subtitle "Generated by Felearn AI" below title (larger as in reference image)
   */
  private async addSubtitleBelowTitle(
    page: any,
    subtitle: string,
    font: any,
    yPosition: number
  ): Promise<number> {
    const pageWidth = page.getWidth();
    const subtitleFontSize = 20; // Larger font size as in reference image

    const textWidth = font.widthOfTextAtSize(subtitle, subtitleFontSize);
    const centerX = (pageWidth - textWidth) / 2; // Perfect center alignment

    page.drawText(subtitle, {
      x: centerX,
      y: yPosition,
      size: subtitleFontSize,
      font: font,
      color: rgb(0.4, 0.4, 0.4) // Subtle gray color
    });

    return yPosition - subtitleFontSize * this.LINE_HEIGHT - 50; // Extra space after subtitle
  }

  /**
   * Add metadata at bottom-left (left-aligned, not centered)
   */
  private async addMetadataBottomLeft(
    page: any,
    story: Story,
    font: any
  ): Promise<void> {
    const pageHeight = page.getHeight();
    const metadataFontSize = 10; // Smaller font size as in reference image
    const metadataSpacing = 12;

    // Get current timestamp for PDF creation
    const pdfCreationTime = new Date().toLocaleString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit'
    });

    // Get story creation date
    const storyCreationDate = new Date(story.createdAt).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    // Get profile username (you may need to adjust this based on your user system)
    const username = story.name || story.userId || 'Anonymous User';

    // Get total slides count
    const totalSlidesCount = story.slides?.length || 0;

    // Get status
    const status = story.isPinned ? 'Pinned' : 'Active';

    // Create metadata array
    const metadata = [
      `PDF Creation Time: ${pdfCreationTime}`,
      `Username: ${username}`,
      `Story Creation Date: ${storyCreationDate}`,
      `Total Slides: ${totalSlidesCount}`,
      `Status: ${status}`
    ];

    // Start drawing from the bottom-left margin
    let currentY = this.PAGE_MARGIN + (metadata.length * metadataFontSize * this.LINE_HEIGHT) + (metadata.length - 1) * metadataSpacing;

    metadata.forEach((line, index) => {
      page.drawText(line, {
        x: this.PAGE_MARGIN, // Left-aligned
        y: currentY,
        size: metadataFontSize,
        font: font,
        color: rgb(0.4, 0.4, 0.4)
      });
      currentY -= metadataFontSize * this.LINE_HEIGHT + metadataSpacing;
    });
  }

  /**
   * Add content to PDF with page breaks
   */
  private async addContent(
    page: any,
    pdfDoc: any,
    content: string,
    font: any,
    yPosition: number
  ): Promise<number> {
    const pageWidth = page.getWidth();
    const pageHeight = page.getHeight();
    const maxWidth = pageWidth - (this.PAGE_MARGIN * 2);

    const paragraphs = content.split('\n\n');

    for (const paragraph of paragraphs) {
      if (paragraph.trim() === '') continue;

      const lines = this.splitTextToFitWidth(paragraph, font, this.FONT_SIZE_BODY, maxWidth);

      // Check if we need a new page
      const requiredHeight = lines.length * this.FONT_SIZE_BODY * this.LINE_HEIGHT;
      if (yPosition - requiredHeight < this.PAGE_MARGIN) {
        page = pdfDoc.addPage(PageSizes.A4);
        yPosition = pageHeight - this.PAGE_MARGIN;
      }

      lines.forEach(line => {
        page.drawText(line, {
          x: this.PAGE_MARGIN,
          y: yPosition,
          size: this.FONT_SIZE_BODY,
          font: font,
          color: rgb(0, 0, 0)
        });
        yPosition -= this.FONT_SIZE_BODY * this.LINE_HEIGHT;
      });

      yPosition -= 10; // Paragraph spacing
    }

    return yPosition;
  }

  /**
   * Add a slide page with responsive image and caption that stay together
   */
  private async addSlidePage(
    page: any,
    pdfDoc: any,
    slide: StorySlide,
    slideNumber: number,
    totalSlides: number,
    captionFont: any,
    bodyFont: any,
    yPosition: number,
    watermarkText: string,
    watermarkOpacity: number
  ): Promise<{ page: any; yPosition: number }> {
    const pageWidth = page.getWidth();
    const pageHeight = page.getHeight();

    // Add slide number at top
    page.drawText(`Slide ${slideNumber} of ${totalSlides}`, {
      x: this.PAGE_MARGIN,
      y: yPosition,
      size: this.FONT_SIZE_SUBTITLE,
      font: bodyFont,
      color: rgb(0.5, 0.5, 0.5)
    });
    yPosition -= this.FONT_SIZE_SUBTITLE * this.LINE_HEIGHT + 20;

    // 🎯 RESPONSIVE LAYOUT: Calculate space needed for both image and caption
    let finalImageWidth = 0;
    let finalImageHeight = 0;
    let captionLines: string[] = [];
    let captionHeight = 0;

    // First, prepare the caption to know its height
    if (slide.text) {
      const caption = this.cleanCaption(slide.text);
      const captionFontSize = 31; // ✅ Reduced to 31 for better balance
      const maxCaptionWidth = pageWidth - (this.PAGE_MARGIN * 4);

      captionLines = this.splitTextToFitWidth(
        caption,
        captionFont,
        captionFontSize,
        maxCaptionWidth
      );

      // Calculate total caption height (including spacing)
      captionHeight = captionLines.length * captionFontSize * this.LINE_HEIGHT + 40; // +40 for spacing
    }

    // Calculate available space for image + caption
    const availableHeight = yPosition - this.PAGE_MARGIN - 100; // Reserve space for watermark
    const spaceForImage = availableHeight - captionHeight;

    // Add image with responsive sizing
    if (slide.image && spaceForImage > 100) { // Minimum 100px for image
      try {
        const imageBytes = await this.loadImageFromUrl(slide.image);
        if (imageBytes) {
          const image = await pdfDoc.embedPng(imageBytes);

          // Calculate optimal image size
          const maxImageWidth = pageWidth - (this.PAGE_MARGIN * 2);
          const naturalImageHeight = (image.height / image.width) * maxImageWidth;

          // ✅ RESPONSIVE: Adjust image size to fit with caption
          if (naturalImageHeight <= spaceForImage) {
            // Image fits naturally
            finalImageWidth = maxImageWidth;
            finalImageHeight = naturalImageHeight;
          } else {
            // ✅ SCALE DOWN: Reduce image size to fit with caption
            finalImageHeight = spaceForImage;
            finalImageWidth = (image.width / image.height) * finalImageHeight;

            // Ensure image doesn't exceed page width
            if (finalImageWidth > maxImageWidth) {
              finalImageWidth = maxImageWidth;
              finalImageHeight = (image.height / image.width) * finalImageWidth;
            }
          }

          // Center the image
          const imageX = (pageWidth - finalImageWidth) / 2;
          const imageY = yPosition - finalImageHeight;

          page.drawImage(image, {
            x: imageX,
            y: imageY,
            width: finalImageWidth,
            height: finalImageHeight
          });

          yPosition = imageY - 30; // Space below image
        }
      } catch (error) {
        console.error('Failed to load image:', error);
        // Add placeholder text
        page.drawText('Image not available', {
          x: this.PAGE_MARGIN,
          y: yPosition,
          size: this.FONT_SIZE_BODY,
          font: bodyFont,
          color: rgb(0.7, 0.7, 0.7)
        });
        yPosition -= this.FONT_SIZE_BODY * this.LINE_HEIGHT + 20;
      }
    }

    // Add caption (now guaranteed to fit on same page)
    if (slide.text && captionLines.length > 0) {
      const captionFontSize = 18; // Consistent with calculation above

      // Add some space before caption
      yPosition -= 20;

      // ✅ GUARANTEED FIT: Caption will fit because we calculated space above
      captionLines.forEach((line) => {
        const textWidth = captionFont.widthOfTextAtSize(line, captionFontSize);
        const centerX = (pageWidth - textWidth) / 2;

        page.drawText(line, {
          x: centerX,
          y: yPosition,
          size: captionFontSize,
          font: captionFont,
          color: rgb(0.2, 0.2, 0.2)
        });
        yPosition -= captionFontSize * this.LINE_HEIGHT + 2;
      });
    }

    // Add watermark
    page.drawText(watermarkText, {
      x: pageWidth - this.PAGE_MARGIN - 100,
      y: this.PAGE_MARGIN,
      size: 10,
      font: bodyFont,
      color: rgb(0.8, 0.8, 0.8)
    });

    return { page, yPosition };
  }

  /**
   * Add acknowledgment page with specified fonts and structure
   */
  private async addAcknowledgmentPage(
    page: any,
    bodyFont: any,
    yPosition: number,
    dosisFont: any,
    consolasFont: any,
    ubuntuLightFont: any,
    pdfDoc: any
  ): Promise<void> {
    const pageWidth = page.getWidth();
    const pageHeight = page.getHeight();

    // Start from top of page
    let currentY = pageHeight - this.PAGE_MARGIN;

    // ACKNOWLEDGEMENT {TITLE} - Bold, large, top-center, simple font
    const titleFontSize = 36;
    const titleText = 'ACKNOWLEDGEMENT';
    const titleWidth = bodyFont.widthOfTextAtSize(titleText, titleFontSize);
    const titleX = (pageWidth - titleWidth) / 2;

    page.drawText(titleText, {
      x: titleX,
      y: currentY,
      size: titleFontSize,
      font: bodyFont,
      color: rgb(0.1, 0.1, 0.1)
    });
    currentY -= titleFontSize * this.LINE_HEIGHT + 40;

    // A Note on Your AI-Generated Story {sub-title} - Dosis font
    const subtitleFontSize = 24;
    const subtitleText = 'A Note on Your AI-Generated Story';
    const subtitleWidth = dosisFont.widthOfTextAtSize(subtitleText, subtitleFontSize);
    const subtitleX = (pageWidth - subtitleWidth) / 2;

    page.drawText(subtitleText, {
      x: subtitleX,
      y: currentY,
      size: subtitleFontSize,
      font: dosisFont,
      color: rgb(0.2, 0.2, 0.2)
    });
    currentY -= subtitleFontSize * this.LINE_HEIGHT + 30;

    // This story was crafted... {text} - Consolas font
    const textFontSize = 12;
    const textContent = "This story was crafted through a creative partnership between you and the Felearn AI platform, powered by Google's Gemini model.";
    const textLines = this.splitTextToFitWidth(textContent, consolasFont, textFontSize, pageWidth - (this.PAGE_MARGIN * 2));

    textLines.forEach(line => {
      page.drawText(line, {
        x: this.PAGE_MARGIN,
        y: currentY,
        size: textFontSize,
        font: consolasFont,
        color: rgb(0.3, 0.3, 0.3)
      });
      currentY -= textFontSize * this.LINE_HEIGHT;
    });
    currentY -= 20;

    // How This Story Was Made {heading} - Simple font
    const headingFontSize = 18;
    const headingText = 'How This Story Was Made';
    page.drawText(headingText, {
      x: this.PAGE_MARGIN,
      y: currentY,
      size: headingFontSize,
      font: bodyFont,
      color: rgb(0.1, 0.1, 0.1)
    });
    currentY -= headingFontSize * this.LINE_HEIGHT + 15;

    // Your Concept: {text} - Consolas font
    const conceptText = "Your Concept: The core idea, characters, and learning objective for this narrative came directly from the prompt you provided.";
    const conceptLines = this.splitTextToFitWidth(conceptText, consolasFont, textFontSize, pageWidth - (this.PAGE_MARGIN * 2));

    conceptLines.forEach(line => {
      page.drawText(line, {
        x: this.PAGE_MARGIN,
        y: currentY,
        size: textFontSize,
        font: consolasFont,
        color: rgb(0.3, 0.3, 0.3)
      });
      currentY -= textFontSize * this.LINE_HEIGHT;
    });
    currentY -= 15;

    // AI Generation: {text} - Consolas font
    const aiText = "AI Generation: Felearn AI used that concept to generate the story text and create the accompanying illustrations.";
    const aiLines = this.splitTextToFitWidth(aiText, consolasFont, textFontSize, pageWidth - (this.PAGE_MARGIN * 2));

    aiLines.forEach(line => {
      page.drawText(line, {
        x: this.PAGE_MARGIN,
        y: currentY,
        size: textFontSize,
        font: consolasFont,
        color: rgb(0.3, 0.3, 0.3)
      });
      currentY -= textFontSize * this.LINE_HEIGHT;
    });
    currentY -= 20;

    // Content & Usage Disclaimer {heading} - Simple font
    const disclaimerHeadingText = 'Content & Usage Disclaimer';
    page.drawText(disclaimerHeadingText, {
      x: this.PAGE_MARGIN,
      y: currentY,
      size: headingFontSize,
      font: bodyFont,
      color: rgb(0.1, 0.1, 0.1)
    });
    currentY -= headingFontSize * this.LINE_HEIGHT + 15;

    // This document was generated... {text} - Consolas font
    const disclaimerText1 = "This document was generated for your personal and educational enjoyment. While we aim for creative and helpful content, please be aware that:";
    const disclaimerLines1 = this.splitTextToFitWidth(disclaimerText1, consolasFont, textFontSize, pageWidth - (this.PAGE_MARGIN * 2));

    disclaimerLines1.forEach(line => {
      page.drawText(line, {
        x: this.PAGE_MARGIN,
        y: currentY,
        size: textFontSize,
        font: consolasFont,
        color: rgb(0.3, 0.3, 0.3)
      });
      currentY -= textFontSize * this.LINE_HEIGHT;
    });
    currentY -= 15;

    // The narrative is AI-generated... {text} - Consolas font
    const disclaimerText2 = "The narrative is AI-generated and may contain fictional elements or factual inaccuracies. Please verify any critical information independently.";
    const disclaimerLines2 = this.splitTextToFitWidth(disclaimerText2, consolasFont, textFontSize, pageWidth - (this.PAGE_MARGIN * 2));

    disclaimerLines2.forEach(line => {
      page.drawText(line, {
        x: this.PAGE_MARGIN,
        y: currentY,
        size: textFontSize,
        font: consolasFont,
        color: rgb(0.3, 0.3, 0.3)
      });
      currentY -= textFontSize * this.LINE_HEIGHT;
    });
    currentY -= 15;

    // You are welcome to use... {text} - Consolas font
    const disclaimerText3 = "You are welcome to use and share this story for non-commercial purposes. Commercial use or redistribution of this content is prohibited.";
    const disclaimerLines3 = this.splitTextToFitWidth(disclaimerText3, consolasFont, textFontSize, pageWidth - (this.PAGE_MARGIN * 2));

    disclaimerLines3.forEach(line => {
      page.drawText(line, {
        x: this.PAGE_MARGIN,
        y: currentY,
        size: textFontSize,
        font: consolasFont,
        color: rgb(0.3, 0.3, 0.3)
      });
      currentY -= textFontSize * this.LINE_HEIGHT;
    });
    currentY -= 30;

    // Generated by Felearn AI {End title} - Ubuntu Light font
    const endTitleFontSize = 16;
    const endTitleText = 'Generated by Felearn AI';
    const endTitleWidth = ubuntuLightFont.widthOfTextAtSize(endTitleText, endTitleFontSize);
    const endTitleX = (pageWidth - endTitleWidth) / 2;

    page.drawText(endTitleText, {
      x: endTitleX,
      y: currentY,
      size: endTitleFontSize,
      font: ubuntuLightFont,
      color: rgb(0.4, 0.4, 0.4)
    });
    currentY -= endTitleFontSize * this.LINE_HEIGHT + 20;

    // Small logo (same as front page but smaller)
    const smallLogoWidth = 139;
    const smallLogoHeight = 41;

    try {
      const imageBytes = await this.loadImageFromUrl('/assets/felearn-logo.png');
      if (imageBytes) {
        const image = await pdfDoc.embedPng(imageBytes);
        const logoX = (pageWidth - smallLogoWidth) / 2;
        const logoY = currentY - smallLogoHeight;

        page.drawImage(image, {
          x: logoX,
          y: logoY,
          width: smallLogoWidth,
          height: smallLogoHeight
        });
        currentY = logoY - 20;
      }
    } catch (error) {
      console.warn('Failed to load small logo for acknowledgment page:', error);
    }

    // Creation Metadata - Consolas font
    const metadataFontSize = 10;
    const currentTime = new Date().toLocaleString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit'
    });

    const metadataText = `Creation Metadata: PDF generated on ${currentTime}`;
    page.drawText(metadataText, {
      x: this.PAGE_MARGIN,
      y: currentY,
      size: metadataFontSize,
      font: consolasFont,
      color: rgb(0.5, 0.5, 0.5)
    });
  }

  /**
   * Load image from URL as bytes
   */
  private async loadImageFromUrl(url: string): Promise<Uint8Array | null> {
    try {
      const response = await fetch(url);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const arrayBuffer = await response.arrayBuffer();
      return new Uint8Array(arrayBuffer);
    } catch (error) {
      console.error('Error loading image from URL:', error);
      return null;
    }
  }



  /**
   * Calculate optimal layout for image and caption to fit together
   */
  private calculateOptimalLayout(
    availableHeight: number,
    imageAspectRatio: number,
    captionLines: number,
    captionFontSize: number,
    pageWidth: number
  ): { imageWidth: number; imageHeight: number; fits: boolean } {
    const maxImageWidth = pageWidth - (this.PAGE_MARGIN * 2);
    const captionHeight = captionLines * captionFontSize * this.LINE_HEIGHT + 60; // +60 for spacing
    const spaceForImage = availableHeight - captionHeight;

    if (spaceForImage < 80) { // Minimum viable image height
      return { imageWidth: 0, imageHeight: 0, fits: false };
    }

    // Try natural image size first
    const naturalImageHeight = maxImageWidth / imageAspectRatio;

    if (naturalImageHeight <= spaceForImage) {
      return {
        imageWidth: maxImageWidth,
        imageHeight: naturalImageHeight,
        fits: true
      };
    }

    // Scale down to fit
    const scaledImageHeight = spaceForImage;
    const scaledImageWidth = scaledImageHeight * imageAspectRatio;

    // Ensure width doesn't exceed page
    if (scaledImageWidth <= maxImageWidth) {
      return {
        imageWidth: scaledImageWidth,
        imageHeight: scaledImageHeight,
        fits: true
      };
    }

    // Width-constrained scaling
    return {
      imageWidth: maxImageWidth,
      imageHeight: maxImageWidth / imageAspectRatio,
      fits: true
    };
  }

  /**
   * Clean caption text with improved handling
   */
  private cleanCaption(caption: string): string {
    if (!caption || typeof caption !== 'string') {
      return 'Image caption';
    }

    let cleaned = caption
      .replace(/\*\*Image \d+:\*\*/g, '') // Remove image markers
      .replace(/Caption:/gi, '') // Remove caption labels
      .replace(/\*\*/g, '') // Remove bold markers
      .replace(/^["']|["']$/g, '') // Remove quotes
      .replace(/^\s*-\s*/, '') // Remove leading dashes
      .replace(/\s+/g, ' ') // Normalize whitespace
      .trim();

    // Extract text from quotes if present
    const quotedMatch = cleaned.match(/"([^"]+)"/);
    if (quotedMatch && quotedMatch[1]) {
      cleaned = quotedMatch[1].trim();
    }

    // Fallback if caption is empty or too short
    if (!cleaned || cleaned.length < 3) {
      return 'Image caption';
    }

    // Limit caption length to prevent overflow
    if (cleaned.length > 200) {
      cleaned = cleaned.substring(0, 197) + '...';
    }

    return cleaned;
  }

  /**
   * Split text to fit within specified width with improved word wrapping
   */
  private splitTextToFitWidth(
    text: string,
    font: any,
    fontSize: number,
    maxWidth: number
  ): string[] {
    const words = text.split(' ');
    const lines: string[] = [];
    let currentLine = '';

    for (const word of words) {
      const testLine = currentLine ? `${currentLine} ${word}` : word;
      const testWidth = font.widthOfTextAtSize(testLine, fontSize);

      if (testWidth <= maxWidth) {
        currentLine = testLine;
      } else {
        if (currentLine) {
          lines.push(currentLine);
          currentLine = word;

          // ✅ Check if single word is still too long
          const singleWordWidth = font.widthOfTextAtSize(word, fontSize);
          if (singleWordWidth > maxWidth) {
            // Break long word into smaller parts
            const brokenWord = this.breakLongWord(word, font, fontSize, maxWidth);
            lines.push(...brokenWord.slice(0, -1)); // Add all but last part
            currentLine = brokenWord[brokenWord.length - 1]; // Keep last part for next line
          }
        } else {
          // Single word is too long, break it
          const brokenWord = this.breakLongWord(word, font, fontSize, maxWidth);
          lines.push(...brokenWord.slice(0, -1));
          currentLine = brokenWord[brokenWord.length - 1];
        }
      }
    }

    if (currentLine) {
      lines.push(currentLine);
    }

    return lines;
  }

  /**
   * Break a long word into smaller parts that fit within maxWidth
   */
  private breakLongWord(
    word: string,
    font: any,
    fontSize: number,
    maxWidth: number
  ): string[] {
    const parts: string[] = [];
    let currentPart = '';

    for (let i = 0; i < word.length; i++) {
      const testPart = currentPart + word[i];
      const testWidth = font.widthOfTextAtSize(testPart, fontSize);

      if (testWidth <= maxWidth) {
        currentPart = testPart;
      } else {
        if (currentPart) {
          parts.push(currentPart + '-'); // Add hyphen for broken words
          currentPart = word[i];
        } else {
          // Even single character is too wide (shouldn't happen with normal fonts)
          parts.push(word[i]);
        }
      }
    }

    if (currentPart) {
      parts.push(currentPart);
    }

    return parts.length > 0 ? parts : [word];
  }

  /**
   * Download PDF file
   */
  private downloadPDF(pdfBytes: Uint8Array, fileName: string): void {
    const blob = new Blob([pdfBytes], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    // Clean up
    setTimeout(() => URL.revokeObjectURL(url), 100);
  }

  /**
   * Sanitize filename
   */
  private sanitizeFileName(fileName: string): string {
    return fileName
      .replace(/[^a-z0-9\s-]/gi, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .trim()
      .toLowerCase()
      .substring(0, 50);
  }
}

// Export singleton instance
export const enhancedPdfExportService = new EnhancedPdfExportService();