import React from 'react';
import { motion } from 'framer-motion';

const AcknowledgmentPage: React.FC = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 to-purple-50 dark:from-gray-900 dark:to-gray-800">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="max-w-4xl mx-auto px-4 py-8"
      >
        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6 md:p-8 mt-12">
          <h1 className="text-3xl md:text-4xl font-bold text-gray-900 dark:text-white mb-2 text-center">
            Acknowledgment
          </h1>
          
          <div className="w-24 h-1 bg-indigo-500 mx-auto mb-8 rounded-full"></div>
          
          <div className="prose prose-lg dark:prose-invert max-w-none">
            <h2 className="text-2xl font-semibold text-gray-800 dark:text-gray-200 mt-8 mb-4">
              A Note on Your AI-Generated Story
            </h2>
            
            <p className="text-gray-600 dark:text-gray-300 mb-6">
              This story was crafted through a creative partnership between you and the Felearn AI platform, powered by Google's Gemini model.
            </p>
            
            <h2 className="text-2xl font-semibold text-gray-800 dark:text-gray-200 mt-8 mb-4">
              How This Story Was Made
            </h2>
            
            <h3 className="text-xl font-medium text-gray-700 dark:text-gray-300 mt-6 mb-2">
              Your Concept
            </h3>
            <p className="text-gray-600 dark:text-gray-300 mb-4">
              The core idea, characters, and learning objective for this narrative came directly from the prompt you provided.
            </p>
            
            <h3 className="text-xl font-medium text-gray-700 dark:text-gray-300 mt-6 mb-2">
              AI Generation
            </h3>
            <p className="text-gray-600 dark:text-gray-300 mb-6">
              Felearn AI used that concept to generate the story text and create the accompanying illustrations.
            </p>
            
            <h2 className="text-2xl font-semibold text-gray-800 dark:text-gray-200 mt-8 mb-4">
              Content & Usage Disclaimer
            </h2>
            
            <p className="text-gray-600 dark:text-gray-300 mb-4">
              This document was generated for your personal and educational enjoyment. While we aim for creative and helpful content, please be aware that:
            </p>
            
            <ul className="list-disc list-inside text-gray-600 dark:text-gray-300 mb-4 ml-4">
              <li>The narrative is AI-generated and may contain fictional elements or factual inaccuracies. Please verify any critical information independently.</li>
              <li>You are welcome to use and share this story for non-commercial purposes. Commercial use or redistribution of this content is prohibited.</li>
            </ul>
            
            <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-6 mt-8">
              <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-200 mb-2">
                Generated by Felearn AI
              </h3>
              <p className="text-gray-600 dark:text-gray-300 text-sm">
                This document was created with the assistance of Felearn AI. For any questions or feedback, please contact our support team.
              </p>
            </div>
          </div>
        </div>
      </motion.div>
    </div>
  );
};

export default AcknowledgmentPage;