const sdk = require('node-appwrite');
const PDFDocument = require('pdfkit');

/**
 * Export Story Function
 * Generates PDF and JSON exports of user stories
 */

// Initialize Appwrite SDK
const client = new sdk.Client();
const databases = new sdk.Databases(client);

client
  .setEndpoint(process.env.APPWRITE_FUNCTION_ENDPOINT || 'https://cloud.appwrite.io/v1')
  .setProject(process.env.APPWRITE_FUNCTION_PROJECT_ID)
  .setKey(process.env.APPWRITE_FUNCTION_API_KEY);

/**
 * Generate PDF export of a story
 */
async function generatePDF(story) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        margin: 50,
        size: 'A4'
      });
      
      const chunks = [];
      
      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(chunks);
        resolve(pdfBuffer);
      });
      doc.on('error', reject);
      
      // Add title
      doc.fontSize(24)
         .font('Helvetica-Bold')
         .text(story.title || 'Untitled Story', { align: 'center' });
      
      doc.moveDown(2);
      
      // Add metadata
      doc.fontSize(10)
         .font('Helvetica')
         .fillColor('gray')
         .text(`Created: ${new Date(story.createdAt).toLocaleDateString()}`, { align: 'right' });
      
      doc.moveDown(1);
      
      // Add story content
      doc.fontSize(12)
         .font('Helvetica')
         .fillColor('black')
         .text(story.content, {
           align: 'justify',
           lineGap: 5
         });
      
      // Add footer
      doc.fontSize(8)
         .fillColor('gray')
         .text('Generated by AI Storytelling Platform', 50, doc.page.height - 50, {
           align: 'center'
         });
      
      doc.end();
      
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Generate JSON export of a story
 */
function generateJSON(story) {
  return {
    id: story.$id,
    title: story.title,
    content: story.content,
    images: Array.isArray(story.images) ? story.images : JSON.parse(story.images || '[]'),
    createdAt: story.createdAt,
    isPinned: story.isPinned,
    exportedAt: new Date().toISOString(),
    version: '1.0'
  };
}

/**
 * Main function handler
 */
module.exports = async ({ req, res, log, error }) => {
  try {
    // Parse request
    const { storyId, format = 'pdf', userId } = req.body || {};
    
    if (!storyId) {
      return res.json({
        success: false,
        error: 'Story ID is required'
      }, 400);
    }
    
    if (!userId) {
      return res.json({
        success: false,
        error: 'User ID is required'
      }, 400);
    }
    
    log(`Exporting story ${storyId} in ${format} format for user ${userId}`);
    
    // Get story from database
    const story = await databases.getDocument(
      process.env.APPWRITE_DATABASE_ID,
      process.env.APPWRITE_STORIES_COLLECTION_ID,
      storyId
    );
    
    // Verify user owns the story
    if (story.userId !== userId) {
      return res.json({
        success: false,
        error: 'Unauthorized: You can only export your own stories'
      }, 403);
    }
    
    let exportData;
    let contentType;
    let filename;
    
    if (format === 'pdf') {
      // Generate PDF
      exportData = await generatePDF(story);
      contentType = 'application/pdf';
      filename = `${story.title || 'story'}.pdf`;
      
    } else if (format === 'json') {
      // Generate JSON
      const jsonData = generateJSON(story);
      exportData = Buffer.from(JSON.stringify(jsonData, null, 2));
      contentType = 'application/json';
      filename = `${story.title || 'story'}.json`;
      
    } else {
      return res.json({
        success: false,
        error: 'Invalid format. Supported formats: pdf, json'
      }, 400);
    }
    
    log(`Successfully generated ${format.toUpperCase()} export for story ${storyId}`);
    
    // Return the file
    return res.send(exportData, 200, {
      'Content-Type': contentType,
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Content-Length': exportData.length.toString()
    });
    
  } catch (err) {
    error(`Export function error: ${err.message}`);
    
    return res.json({
      success: false,
      error: 'Failed to export story',
      details: process.env.NODE_ENV === 'development' ? err.message : undefined
    }, 500);
  }
};